Add Ethereum signing test
robot-ux/wallet-core-example pull request #2
Opened 2022-06-21 08:19 UTC by hewigovens

2022-06-21 08:35 UTC, merged

2025-05-16 22:44 UTC, walteazy approved these changes

2025-07-22 23:38 UTC, Rezazare113 reviewed
"postinstall": "mkdir -pv public/static/js && cp node_modules/@trustwallet/wallet-core/dist/lib/wallet-core.* public/static/js"  "name": "wallet-core-example",    "build": "react-app-rewired build",    "start": "react-app-rewired start",5c5953689908f23b1cdc33fb72be71e63de534bb

2025-07-22 23:46 UTC, Rezazare113 requested changes

2025-07-22 23:46 UTC, Rezazare113 commented on package.json
> +    "postinstall": "mkdir -pv public/static/js && cp node_modules/@trustwallet/wallet-core/dist/lib/wallet-core.* public/static/js"
package.jsonsrc/initWasm.tsscripts/test.jspackage.jsonsrc/initWasm.ts85323fd945d199a530a0be3cfe4a0835819b3129scripts/test.js85323fd945d199a530a0be3cfe4a0835819b3- [ ] 129
```suggestion
    "postinstall": "mkdir -pv public/static/js && cp node_modules/@trustwallet/wallet-core/dist/lib/wallet- - # [ ] -core.* public/static/js"[]()@[]()85323fd945d199a530a0be3cfe4a0835819b3129**
```suggestion
    "postinstall": "mkdir -pv public/static/js && cp node_modules/@trustwallet/wallet-core/dist/lib/wallet-core.* public/static/js"src/App.tsx
```suggestion
    "postinstall": "mkdir -pv public/static/js && cp node_modules/@trustwallet/wallet-core/dist/lib/wallet-core.* public/static/js"85323fd945d199a530a0be3cfe4a0835819b3129

```

```
**
```

2025-10-25 22:27 UTC, walteazy approved these changes